### ISSUE TITLE
The question about "Error about Submitted Files("path"...)"

### ISSUE THREAD

**Issue by JJingH** [LiuZhihhxx/KDD#1]
Excuse me, sorry to disturb you. I would like to ask whether you have solved this problem, as I have bothered by the same question for a long time. If possible, I would like to ask for a solution. Thank you sincerely !

**Comment by LiuZhihhxx** [comment]
Seems like we are both Chinese so let's just discuss in Chinese.

我已经解决这个问题了，其症结在于：
predict.py中的model_dir(即存放模型的文件夹名)取决于prepare.py中的envs[file_name]，也就是你建模用到的csv数据文件名，如果你文件名有更改，最好检查一下这两个是不是一致的。
因为我对原数据做了处理，改了csv的文件名，一开始忘了在prepare.py中声明，使用了之前的默认值"wtbdata_245days.csv"，进而导致了这种情况。
互相帮助哈~

**Comment by JJingH** [comment]
感谢感谢，自己也解决了这个问题（虽然又产生了新的问题），不过还是很感谢，自己再琢磨琢磨，再次感谢！

如果有什么能帮到你的地方，一定帮助~~
